services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
    ports:
      - "3306:3306"
    networks:
      - eng-network
  web: 
    build: .
    restart: always
    command: uvicorn --host 0.0.0.0 main:app
    ports: 
      - "8000:8000"
    networks:
      - eng-network

networks:
  eng-network: